# Database Configuration
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/showspace
db.username=postgres
db.password=postgres

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.ddl-auto=update
